import './SLADetailDrawer.css';
import type { Report } from './ReportsTable';
import type { ReportFormat } from '../../hooks/useReports';

interface ReportDetailDrawerProps {
  report: Report;
  user: any;
  onExport: (reportId: string, format: ReportFormat) => void;
  onClose: () => void;
  isExporting?: boolean;
}

export default function ReportDetailDrawer({
  report,
  onExport,
  onClose,
  isExporting
}: ReportDetailDrawerProps) {
  const id = report._id || report.id || '';

  return (
    <div className="drawer-overlay" onClick={onClose}>
      <div className="drawer" onClick={(e) => e.stopPropagation()}>
        <div className="drawer-header">
          <h3>{report.name || 'Report'}</h3>
          <button onClick={onClose} className="btn-close">✕</button>
        </div>

        <div className="drawer-content">
          <div className="field-group">
            <label>Type</label>
            <p className="field-value">{report.type || '—'}</p>
          </div>
          <div className="field-group">
            <label>Frequency</label>
            <p className="field-value">{report.frequency || '—'}</p>
          </div>
          <div className="field-group">
            <label>Generated</label>
            <p className="field-value">
              {report.generatedAt ? new Date(report.generatedAt).toLocaleString() : '—'}
            </p>
          </div>
          <div className="field-group">
            <label>Generated by</label>
            <p className="field-value">{report.generatedBy || '—'}</p>
          </div>
          <div className="field-group">
            <label>Rows</label>
            <p className="field-value">{report.rowCount ?? '—'}</p>
          </div>

          <div className="field-group">
            <label>Export</label>
            <div className="export-buttons">
              {(['pdf', 'xlsx', 'csv'] as ReportFormat[]).map((fmt) => (
                <button
                  key={fmt}
                  type="button"
                  className="btn-secondary"
                  disabled={isExporting}
                  onClick={() => onExport(id, fmt)}
                >
                  {fmt.toUpperCase()}
                </button>
              ))}
            </div>
          </div>

          <div className="drawer-actions">
            <button onClick={onClose} className="btn-secondary">Close</button>
          </div>
        </div>
      </div>
    </div>
  );
}
